using Raun;
using System.ComponentModel;

namespace AppointmentTests;

/// <summary>
/// Scenarios authored as plain C#: instance methods of a class deriving from the suite's
/// <see cref="AppointmentSuite"/>, so <c>Given</c>, <c>When</c> and <c>Then</c> are its properties. The
/// generator lowers each body into a graph the runtime runs, reporting every step as its own test.
/// Nothing executes these bodies directly — they are source for the generator.
/// </summary>
[DisplayName("Appointment booking")]
public sealed class Scenarios : AppointmentSuite
{
    // Linear: statements run in source order. CreateAppointment depends on both arrange steps.
    [Scenario("customer books an appointment")]
    public async Task Booking()
    {
        var patient = await Given.PatientExists("Jane");
        var slot = await Given.AvailableSlot();

        var appointment = await When.CreateAppointment(patient, slot);

        await Then.AppointmentExists(appointment);
    }

    // Conditionals: the condition is an ordinary awaited step, so it is discovered, timed, and
    // reported like any other. Exactly one arm runs; the other is reported not-taken (never green),
    // and the two definitions of `appointment` merge at the closing brace.
    [Scenario("priority patients get an urgent appointment")]
    public async Task BookingWithPriorityRouting()
    {
        var patient = await Given.PatientExists("Alice");
        var slot = await Given.AvailableSlot();

        Appointment appointment;
        if (await Given.PatientIsPriority(patient))
            appointment = await When.CreateUrgentAppointment(patient, slot);
        else
            appointment = await When.CreateAppointment(patient, slot);

        await Then.AppointmentExists(appointment);
    }

    // Explicit fork/join with an awaited tuple: the two arrange steps run in parallel after the
    // clean step, and CreateAppointment waits for both.
    [Scenario("customer books with parallel arrange")]
    public async Task BookingWithParallelArrange()
    {
        await Given.DatabaseIsClean();

        var (patient, slot) = await (
            Given.PatientExists("Jane"),
            Given.AvailableSlot());

        var appointment = await When.CreateAppointment(patient, slot);

        await Then.AppointmentExists(appointment);
    }

    // Homogeneous bulk parallelism with an awaited explicit array.
    [Scenario("bulk user import")]
    public async Task ImportUsers()
    {
        var users = await new[]
        {
            Given.UserExists("alice"),
            Given.UserExists("bob"),
        };

        var import = await When.ImportUsers(users);

        await Then.ImportShouldContainUsers(import, 2);
    }

    // The same bulk form generated by LINQ; the constant range is unrolled into one step per user.
    [Scenario("bulk user import via LINQ")]
    public async Task ImportUsersViaLinq()
    {
        var users = await Enumerable.Range(1, 3)
            .Select(i => Given.UserExists($"user-{i}"))
            .ToArray();

        var import = await When.ImportUsers(users);

        await Then.ImportShouldContainUsers(import, 3);
    }
}
