//HintName: RaunScenarios.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
#line hidden
using Raun;
using System.Linq;
using System.Threading.Tasks;
using Demo;

namespace Raun.Generated
{
    internal static class RaunGenerated
    {
        public static global::System.Collections.Generic.IReadOnlyList<global::Raun.Model.ScenarioDefinition> CreateAll() => new global::Raun.Model.ScenarioDefinition[]
        {
            Scenario_Demo_ArrayScenarios_Import()
        };
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Initialize()
        {
            global::Raun.ScenarioRegistry.Register("Demo.ArrayScenarios.Import", Scenario_Demo_ArrayScenarios_Import);
        }

        public static global::Raun.Model.ScenarioDefinition Scenario_Demo_ArrayScenarios_Import()
        {
            var nodes = new global::Raun.Model.ScenarioNode[5];
            nodes[0] = new global::Raun.Model.ScenarioNode
            {
                Index = 0,
                StepId = "409989c70df28d22",
                Phase = "Given",
                OperationName = "UserExists",
                DisplayNameTemplate = "user alice exists",
                SourceFile = "",
                SourceLine = 78,
                GroupId = "g0",
                Timeout = null,
                DependsOn = new int[]
                {
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await Given.UserExists("alice");
#line hidden
                    return (object? )__r;
                }
            };
            nodes[1] = new global::Raun.Model.ScenarioNode
            {
                Index = 1,
                StepId = "e3a937d2fe56991b",
                Phase = "Given",
                OperationName = "UserExists",
                DisplayNameTemplate = "user bob exists",
                SourceFile = "",
                SourceLine = 79,
                GroupId = "g0",
                Timeout = null,
                DependsOn = new int[]
                {
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await Given.UserExists("bob");
#line hidden
                    return (object? )__r;
                }
            };
            nodes[2] = new global::Raun.Model.ScenarioNode
            {
                Index = 2,
                StepId = "e3d315bf20316dec",
                Phase = "When",
                OperationName = "ImportUsers",
                DisplayNameTemplate = "importing users",
                SourceFile = "",
                SourceLine = 82,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0,
                    1
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await When.ImportUsers(new global::Demo.User[] { __inputs.Get<global::Demo.User>(0), __inputs.Get<global::Demo.User>(1) });
#line hidden
                    return (object? )__r;
                }
            };
            nodes[3] = new global::Raun.Model.ScenarioNode
            {
                Index = 3,
                StepId = "e54e734040605c4a",
                Phase = "Then",
                OperationName = "ImportShouldContainUsers",
                DisplayNameTemplate = "the import should contain the users",
                SourceFile = "",
                SourceLine = 83,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0,
                    1,
                    2
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    await Then.ImportShouldContainUsers(__inputs.Get<global::Demo.Import>(2), new global::Demo.User[] { __inputs.Get<global::Demo.User>(0), __inputs.Get<global::Demo.User>(1) });
#line hidden
                    return (object? )null;
                }
            };
            nodes[4] = new global::Raun.Model.ScenarioNode
            {
                Index = 4,
                StepId = "afa7e3343e6dbe45",
                Phase = "Then",
                OperationName = "Teardown",
                DisplayNameTemplate = "Teardown",
                SourceFile = null,
                SourceLine = 0,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                },
                IsTeardown = true,
                Invoke = static (__inputs, __ctx) => global::System.Threading.Tasks.Task.FromResult<object?>(null)
            };
            return new global::Raun.Model.ScenarioDefinition
            {
                ScenarioId = "903e3e1cb803db83",
                DisplayName = "array import",
                MethodName = "Demo.ArrayScenarios.Import",
                Namespace = "Demo",
                TypeName = "ArrayScenarios",
                ClassDisplayName = null,
                SourceFile = "",
                SourceLine = 74,
                Timeout = null,
                TeardownPolicy = (global::Raun.Run)0,
                Nodes = nodes
            };
        }
    }
}
