//HintName: RaunScenario.UsesDemo_UsesScenarios_ClearAndRemind.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
#line hidden
using Raun;
using System.Linq;
using System.Threading.Tasks;
using UsesDemo;

namespace Raun.Generated
{
    internal static partial class RaunGenerated
    {
        public static global::Raun.Model.ScenarioDefinition Scenario_UsesDemo_UsesScenarios_ClearAndRemind()
        {
            var nodes = new global::Raun.Model.ScenarioNode[4];
            nodes[0] = new global::Raun.Model.ScenarioNode
            {
                Index = 0,
                StepId = "8e029ff24cbddd97",
                Phase = "Setup",
                OperationName = "Setup",
                DisplayNameTemplate = "Setup",
                SourceFile = null,
                SourceLine = 0,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                },
                IsSetup = true,
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await global::Raun.ScenarioScope.SetupAsync<global::Raun.NoWorld>(__ctx);
#line hidden
                    return (object? )__r;
                }
            };
            nodes[1] = new global::Raun.Model.ScenarioNode
            {
                Index = 1,
                StepId = "f249cffef8ebb82c",
                Phase = "Given",
                OperationName = "ScheduleIsEmpty",
                DisplayNameTemplate = "the schedule is empty",
                SourceFile = "",
                SourceLine = 46,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    await __inputs.Get<global::Raun.ScenarioScope<global::Raun.NoWorld>>(0).Steps<global::UsesDemo.UsesGiven>().ScheduleIsEmpty();
#line hidden
                    return (object? )null;
                }
            };
            nodes[2] = new global::Raun.Model.ScenarioNode
            {
                Index = 2,
                StepId = "9475f0063ecc0822",
                Phase = "When",
                OperationName = "ReminderIsSent",
                DisplayNameTemplate = "a reminder is sent",
                SourceFile = "",
                SourceLine = 47,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0,
                    1
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    await __inputs.Get<global::Raun.ScenarioScope<global::Raun.NoWorld>>(0).Steps<global::UsesDemo.UsesWhen>().ReminderIsSent();
#line hidden
                    return (object? )null;
                }
            };
            nodes[3] = new global::Raun.Model.ScenarioNode
            {
                Index = 3,
                StepId = "1d1c94720a888a0a",
                Phase = "Then",
                OperationName = "Teardown",
                DisplayNameTemplate = "Teardown",
                SourceFile = null,
                SourceLine = 0,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                },
                IsTeardown = true,
                Invoke = static (__inputs, __ctx) => global::System.Threading.Tasks.Task.FromResult<object?>(null)
            };
            return new global::Raun.Model.ScenarioDefinition
            {
                ScenarioId = "df09c8dfa69bf244",
                DisplayName = "clears and reminds",
                MethodName = "UsesDemo.UsesScenarios.ClearAndRemind",
                Namespace = "UsesDemo",
                TypeName = "UsesScenarios",
                ClassDisplayName = null,
                SourceFile = "",
                SourceLine = 44,
                Timeout = null,
                TeardownPolicy = (global::Raun.Run)0,
                Nodes = nodes,
                Method = typeof(global::UsesDemo.UsesScenarios).GetMethod("ClearAndRemind", global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.DeclaredOnly),
                Uses = new global::Raun.ContendedResourceUse[]
                {
                    new global::Raun.ContendedResourceUse(typeof(global::UsesDemo.Audit), global::Raun.LockMode.Shared),
                    new global::Raun.ContendedResourceUse(typeof(global::UsesDemo.Database), global::Raun.LockMode.Exclusive),
                    new global::Raun.ContendedResourceUse(typeof(global::UsesDemo.Smtp), global::Raun.LockMode.Shared)
                }
            };
        }
    }
}
