//HintName: RaunScenarios.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
#line hidden
using Raun;
using System.Linq;
using System.Threading.Tasks;

namespace Raun.Generated
{
    internal static partial class RaunGenerated
    {
        public static global::System.Collections.Generic.IReadOnlyList<global::Raun.Model.ScenarioDefinition> CreateAll() => new global::Raun.Model.ScenarioDefinition[]
        {
            Scenario_OutcomeDemo_SwitchScenarios_Route(),
            Scenario_OutcomeDemo_SwitchScenarios_NoMatch(),
            Scenario_OutcomeDemo_SwitchScenarios_Merge()
        };
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Initialize()
        {
            global::Raun.ScenarioRegistry.Register("OutcomeDemo.SwitchScenarios.Route", Scenario_OutcomeDemo_SwitchScenarios_Route);
            global::Raun.ScenarioRegistry.Register("OutcomeDemo.SwitchScenarios.NoMatch", Scenario_OutcomeDemo_SwitchScenarios_NoMatch);
            global::Raun.ScenarioRegistry.Register("OutcomeDemo.SwitchScenarios.Merge", Scenario_OutcomeDemo_SwitchScenarios_Merge);
        }
    }
}
