//HintName: RaunScenario.OutcomeDemo_SwitchScenarios_Merge.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
#line hidden
using Raun;
using System.Linq;
using System.Threading.Tasks;
using OutcomeDemo;

namespace Raun.Generated
{
    internal static partial class RaunGenerated
    {
        public static global::Raun.Model.ScenarioDefinition Scenario_OutcomeDemo_SwitchScenarios_Merge()
        {
            var nodes = new global::Raun.Model.ScenarioNode[9];
            nodes[0] = new global::Raun.Model.ScenarioNode
            {
                Index = 0,
                StepId = "7885d7a197547823",
                Phase = "Setup",
                OperationName = "Setup",
                DisplayNameTemplate = "Setup",
                SourceFile = null,
                SourceLine = 0,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                },
                IsSetup = true,
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await global::Raun.ScenarioScope.SetupAsync<global::Raun.NoWorld>(__ctx);
#line hidden
                    return (object? )__r;
                }
            };
            nodes[1] = new global::Raun.Model.ScenarioNode
            {
                Index = 1,
                StepId = "00873c340d208618",
                Phase = "When",
                OperationName = "Submit",
                DisplayNameTemplate = "submitting order ok",
                SourceFile = "",
                SourceLine = 103,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await __inputs.Get<global::Raun.ScenarioScope<global::Raun.NoWorld>>(0).Steps<global::OutcomeDemo.OutcomeWhen>().Submit("ok");
#line hidden
                    return (object? )__r;
                }
            };
            nodes[2] = new global::Raun.Model.ScenarioNode
            {
                Index = 2,
                StepId = "2ec1d2b2db17d30f",
                Phase = "When",
                OperationName = "Submit",
                DisplayNameTemplate = "submitting order no",
                SourceFile = "",
                SourceLine = 104,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0,
                    1
                },
                SelectArm = static __inputs =>
                {
                    int __arm = -1;
                    switch (__inputs.Get<global::OutcomeDemo.Outcome>(2))
                    {
                        case global::OutcomeDemo.Rejected:
                            __arm = 0;
                            break;
                        default:
                            __arm = 1;
                            break;
                    }

                    return __arm;
                },
                Arms = new string[]
                {
                    "case Rejected",
                    "default"
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await __inputs.Get<global::Raun.ScenarioScope<global::Raun.NoWorld>>(0).Steps<global::OutcomeDemo.OutcomeWhen>().Submit("no");
#line hidden
                    return (object? )__r;
                }
            };
            nodes[3] = new global::Raun.Model.ScenarioNode
            {
                Index = 3,
                StepId = "8dac7c8f4617ab54",
                Phase = "When",
                OperationName = "Submit",
                DisplayNameTemplate = "submitting order fast",
                SourceFile = "",
                SourceLine = 107,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0,
                    2
                },
                Guards = new global::Raun.Model.Guard[]
                {
                    new global::Raun.Model.Guard(2, 0)
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await __inputs.Get<global::Raun.ScenarioScope<global::Raun.NoWorld>>(0).Steps<global::OutcomeDemo.OutcomeWhen>().Submit("fast");
#line hidden
                    return (object? )__r;
                }
            };
            nodes[4] = new global::Raun.Model.ScenarioNode
            {
                Index = 4,
                StepId = "fa67fd593f020ba5",
                Phase = "When",
                OperationName = "Unchanged",
                DisplayNameTemplate = "«outcome unchanged»",
                SourceFile = null,
                SourceLine = 0,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                },
                Guards = new global::Raun.Model.Guard[]
                {
                    new global::Raun.Model.Guard(2, 1)
                },
                MergeSources = new int[]
                {
                    1
                },
                IsSynthetic = true,
                Invoke = static (__inputs, __ctx) => global::System.Threading.Tasks.Task.FromResult<object?>(null)
            };
            nodes[5] = new global::Raun.Model.ScenarioNode
            {
                Index = 5,
                StepId = "df877d9544476221",
                Phase = "When",
                OperationName = "Merge",
                DisplayNameTemplate = "«merge outcome»",
                SourceFile = null,
                SourceLine = 0,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                },
                MergeSources = new int[]
                {
                    3,
                    4
                },
                IsSynthetic = true,
                Invoke = static (__inputs, __ctx) => global::System.Threading.Tasks.Task.FromResult<object?>(null)
            };
            nodes[6] = new global::Raun.Model.ScenarioNode
            {
                Index = 6,
                StepId = "fc7b56ad69d3625a",
                Phase = "When",
                OperationName = "Submit",
                DisplayNameTemplate = "submitting order x",
                SourceFile = "",
                SourceLine = 113,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0,
                    5
                },
                WaitsFor = new int[]
                {
                    3
                },
                SelectArm = static __inputs => (__inputs.Get<global::OutcomeDemo.Outcome>(6)is global::OutcomeDemo.Pending) ? 0 : 1,
                Arms = new string[]
                {
                    "is Pending",
                    "else"
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await __inputs.Get<global::Raun.ScenarioScope<global::Raun.NoWorld>>(0).Steps<global::OutcomeDemo.OutcomeWhen>().Submit("x");
#line hidden
                    return (object? )__r;
                }
            };
            nodes[7] = new global::Raun.Model.ScenarioNode
            {
                Index = 7,
                StepId = "d762db11917dca90",
                Phase = "Then",
                OperationName = "Shipped",
                DisplayNameTemplate = "shipment {shipment} scheduled",
                SourceFile = "",
                SourceLine = 114,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0,
                    5,
                    6
                },
                Guards = new global::Raun.Model.Guard[]
                {
                    new global::Raun.Model.Guard(6, 0)
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    await __inputs.Get<global::Raun.ScenarioScope<global::Raun.NoWorld>>(0).Steps<global::OutcomeDemo.OutcomeThen>().Shipped(((global::OutcomeDemo.Accepted)__inputs.Get<global::OutcomeDemo.Outcome>(5)).Shipment);
#line hidden
                    return (object? )null;
                },
                FormatDisplayName = static __inputs => "shipment " + (((global::OutcomeDemo.Accepted)__inputs.Get<global::OutcomeDemo.Outcome>(5)).Shipment) + " scheduled"
            };
            nodes[8] = new global::Raun.Model.ScenarioNode
            {
                Index = 8,
                StepId = "944d5d4e46081196",
                Phase = "Then",
                OperationName = "Teardown",
                DisplayNameTemplate = "Teardown",
                SourceFile = null,
                SourceLine = 0,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                },
                IsTeardown = true,
                Invoke = static (__inputs, __ctx) => global::System.Threading.Tasks.Task.FromResult<object?>(null)
            };
            return new global::Raun.Model.ScenarioDefinition
            {
                ScenarioId = "fe6a81e216f677cf",
                DisplayName = "a local merges across switch arms",
                MethodName = "OutcomeDemo.SwitchScenarios.Merge",
                Namespace = "OutcomeDemo",
                TypeName = "SwitchScenarios",
                ClassDisplayName = null,
                SourceFile = "",
                SourceLine = 101,
                Timeout = null,
                TeardownPolicy = (global::Raun.Run)0,
                Nodes = nodes,
                Method = typeof(global::OutcomeDemo.SwitchScenarios).GetMethod("Merge", global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.DeclaredOnly)
            };
        }
    }
}
