//HintName: RaunScenario.OutcomeDemo_SwitchScenarios_NoMatch.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
#line hidden
using Raun;
using System.Linq;
using System.Threading.Tasks;
using OutcomeDemo;

namespace Raun.Generated
{
    internal static partial class RaunGenerated
    {
        public static global::Raun.Model.ScenarioDefinition Scenario_OutcomeDemo_SwitchScenarios_NoMatch()
        {
            var nodes = new global::Raun.Model.ScenarioNode[8];
            nodes[0] = new global::Raun.Model.ScenarioNode
            {
                Index = 0,
                StepId = "0d235f35e7cf54f9",
                Phase = "Setup",
                OperationName = "Setup",
                DisplayNameTemplate = "Setup",
                SourceFile = null,
                SourceLine = 0,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                },
                IsSetup = true,
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await global::Raun.ScenarioScope.SetupAsync<global::Raun.NoWorld>(__ctx);
#line hidden
                    return (object? )__r;
                }
            };
            nodes[1] = new global::Raun.Model.ScenarioNode
            {
                Index = 1,
                StepId = "a51780e4e83d6fad",
                Phase = "When",
                OperationName = "Submit",
                DisplayNameTemplate = "submitting order pending",
                SourceFile = "",
                SourceLine = 87,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0
                },
                SelectArm = static __inputs =>
                {
                    int __arm = -1;
                    switch (__inputs.Get<global::OutcomeDemo.Outcome>(1))
                    {
                        case global::OutcomeDemo.Accepted accepted:
                            __arm = 0;
                            break;
                        case global::OutcomeDemo.Rejected rejected:
                            __arm = 1;
                            break;
                    }

                    return __arm;
                },
                Arms = new string[]
                {
                    "case Accepted accepted",
                    "case Rejected rejected"
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await __inputs.Get<global::Raun.ScenarioScope<global::Raun.NoWorld>>(0).Steps<global::OutcomeDemo.OutcomeWhen>().Submit("pending");
#line hidden
                    return (object? )__r;
                }
            };
            nodes[2] = new global::Raun.Model.ScenarioNode
            {
                Index = 2,
                StepId = "99a6ff4c0f03b5ef",
                Phase = "When",
                OperationName = "Case",
                DisplayNameTemplate = "«case Accepted accepted»",
                SourceFile = null,
                SourceLine = 0,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    1
                },
                Guards = new global::Raun.Model.Guard[]
                {
                    new global::Raun.Model.Guard(1, 0)
                },
                IsSynthetic = true,
                Invoke = static (__inputs, __ctx) =>
                {
                    var __v = __inputs.Get<global::OutcomeDemo.Outcome>(1);
                    if (__v is global::OutcomeDemo.Accepted accepted)
                        return global::System.Threading.Tasks.Task.FromResult<object?>(accepted);
                    throw new global::System.InvalidOperationException("A case node ran but its arm's pattern did not match; this is a Raun generator bug.");
                }
            };
            nodes[3] = new global::Raun.Model.ScenarioNode
            {
                Index = 3,
                StepId = "795b09b70e218eca",
                Phase = "Then",
                OperationName = "Shipped",
                DisplayNameTemplate = "shipment {shipment} scheduled",
                SourceFile = "",
                SourceLine = 90,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0,
                    1,
                    2
                },
                Guards = new global::Raun.Model.Guard[]
                {
                    new global::Raun.Model.Guard(1, 0)
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    await __inputs.Get<global::Raun.ScenarioScope<global::Raun.NoWorld>>(0).Steps<global::OutcomeDemo.OutcomeThen>().Shipped(__inputs.Get<global::OutcomeDemo.Accepted>(2).Shipment);
#line hidden
                    return (object? )null;
                },
                FormatDisplayName = static __inputs => "shipment " + (__inputs.Get<global::OutcomeDemo.Accepted>(2).Shipment) + " scheduled"
            };
            nodes[4] = new global::Raun.Model.ScenarioNode
            {
                Index = 4,
                StepId = "99a6fe4c0f03b43c",
                Phase = "When",
                OperationName = "Case",
                DisplayNameTemplate = "«case Rejected rejected»",
                SourceFile = null,
                SourceLine = 0,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    1
                },
                Guards = new global::Raun.Model.Guard[]
                {
                    new global::Raun.Model.Guard(1, 1)
                },
                IsSynthetic = true,
                Invoke = static (__inputs, __ctx) =>
                {
                    var __v = __inputs.Get<global::OutcomeDemo.Outcome>(1);
                    if (__v is global::OutcomeDemo.Rejected rejected)
                        return global::System.Threading.Tasks.Task.FromResult<object?>(rejected);
                    throw new global::System.InvalidOperationException("A case node ran but its arm's pattern did not match; this is a Raun generator bug.");
                }
            };
            nodes[5] = new global::Raun.Model.ScenarioNode
            {
                Index = 5,
                StepId = "d5e8bdb3b2611d93",
                Phase = "Then",
                OperationName = "Told",
                DisplayNameTemplate = "customer told {reason}",
                SourceFile = "",
                SourceLine = 93,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0,
                    1,
                    4
                },
                Guards = new global::Raun.Model.Guard[]
                {
                    new global::Raun.Model.Guard(1, 1)
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    await __inputs.Get<global::Raun.ScenarioScope<global::Raun.NoWorld>>(0).Steps<global::OutcomeDemo.OutcomeThen>().Told(__inputs.Get<global::OutcomeDemo.Rejected>(4).Reason);
#line hidden
                    return (object? )null;
                },
                FormatDisplayName = static __inputs => "customer told " + (__inputs.Get<global::OutcomeDemo.Rejected>(4).Reason)
            };
            nodes[6] = new global::Raun.Model.ScenarioNode
            {
                Index = 6,
                StepId = "73c1f41366f52d41",
                Phase = "Then",
                OperationName = "StillPending",
                DisplayNameTemplate = "order pending",
                SourceFile = "",
                SourceLine = 97,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0,
                    1
                },
                WaitsFor = new int[]
                {
                    3,
                    5
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    await __inputs.Get<global::Raun.ScenarioScope<global::Raun.NoWorld>>(0).Steps<global::OutcomeDemo.OutcomeThen>().StillPending();
#line hidden
                    return (object? )null;
                }
            };
            nodes[7] = new global::Raun.Model.ScenarioNode
            {
                Index = 7,
                StepId = "d05ad07fb9c28b2c",
                Phase = "Then",
                OperationName = "Teardown",
                DisplayNameTemplate = "Teardown",
                SourceFile = null,
                SourceLine = 0,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                },
                IsTeardown = true,
                Invoke = static (__inputs, __ctx) => global::System.Threading.Tasks.Task.FromResult<object?>(null)
            };
            return new global::Raun.Model.ScenarioDefinition
            {
                ScenarioId = "135d7b56f0f0f063",
                DisplayName = "no arm matches",
                MethodName = "OutcomeDemo.SwitchScenarios.NoMatch",
                Namespace = "OutcomeDemo",
                TypeName = "SwitchScenarios",
                ClassDisplayName = null,
                SourceFile = "",
                SourceLine = 85,
                Timeout = null,
                TeardownPolicy = (global::Raun.Run)0,
                Nodes = nodes,
                Method = typeof(global::OutcomeDemo.SwitchScenarios).GetMethod("NoMatch", global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.DeclaredOnly)
            };
        }
    }
}
