//HintName: RaunScenario.CondDemo_IfElseScenarios_Routing.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
#line hidden
using Raun;
using System.Linq;
using System.Threading.Tasks;
using CondDemo;

namespace Raun.Generated
{
    internal static partial class RaunGenerated
    {
        public static global::Raun.Model.ScenarioDefinition Scenario_CondDemo_IfElseScenarios_Routing()
        {
            var nodes = new global::Raun.Model.ScenarioNode[8];
            nodes[0] = new global::Raun.Model.ScenarioNode
            {
                Index = 0,
                StepId = "2b555219834cb57e",
                Phase = "Setup",
                OperationName = "Setup",
                DisplayNameTemplate = "Setup",
                SourceFile = null,
                SourceLine = 0,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                },
                IsSetup = true,
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await global::Raun.ScenarioScope.SetupAsync<global::Raun.NoWorld>(__ctx);
#line hidden
                    return (object? )__r;
                }
            };
            nodes[1] = new global::Raun.Model.ScenarioNode
            {
                Index = 1,
                StepId = "306d12ecb4c82c3e",
                Phase = "Given",
                OperationName = "PatientExists",
                DisplayNameTemplate = "patient Jane exists",
                SourceFile = "",
                SourceLine = 78,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await __inputs.Get<global::Raun.ScenarioScope<global::Raun.NoWorld>>(0).Steps<global::CondDemo.CondGiven>().PatientExists("Jane");
#line hidden
                    return (object? )__r;
                }
            };
            nodes[2] = new global::Raun.Model.ScenarioNode
            {
                Index = 2,
                StepId = "cbea19ac8f9c6e99",
                Phase = "Given",
                OperationName = "IsPriority",
                DisplayNameTemplate = "the patient is priority",
                SourceFile = "",
                SourceLine = 81,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0,
                    1
                },
                EvaluateCondition = static __o => ((bool)__o!) ? true : false,
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await __inputs.Get<global::Raun.ScenarioScope<global::Raun.NoWorld>>(0).Steps<global::CondDemo.CondGiven>().IsPriority();
#line hidden
                    return (object? )__r;
                }
            };
            nodes[3] = new global::Raun.Model.ScenarioNode
            {
                Index = 3,
                StepId = "cb02a08387cc6e69",
                Phase = "When",
                OperationName = "CreateUrgent",
                DisplayNameTemplate = "creating an urgent appointment",
                SourceFile = "",
                SourceLine = 82,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0,
                    1,
                    2
                },
                Guards = new global::Raun.Model.Guard[]
                {
                    new global::Raun.Model.Guard(2, true)
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await __inputs.Get<global::Raun.ScenarioScope<global::Raun.NoWorld>>(0).Steps<global::CondDemo.CondWhen>().CreateUrgent(__inputs.Get<global::CondDemo.Patient>(1));
#line hidden
                    return (object? )__r;
                }
            };
            nodes[4] = new global::Raun.Model.ScenarioNode
            {
                Index = 4,
                StepId = "2e182524c700f5e1",
                Phase = "When",
                OperationName = "CreateStandard",
                DisplayNameTemplate = "creating a standard appointment",
                SourceFile = "",
                SourceLine = 84,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0,
                    1,
                    2
                },
                Guards = new global::Raun.Model.Guard[]
                {
                    new global::Raun.Model.Guard(2, false)
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await __inputs.Get<global::Raun.ScenarioScope<global::Raun.NoWorld>>(0).Steps<global::CondDemo.CondWhen>().CreateStandard(__inputs.Get<global::CondDemo.Patient>(1));
#line hidden
                    return (object? )__r;
                }
            };
            nodes[5] = new global::Raun.Model.ScenarioNode
            {
                Index = 5,
                StepId = "7f4b5e73d9c4311d",
                Phase = "When",
                OperationName = "Merge",
                DisplayNameTemplate = "«merge appointment»",
                SourceFile = null,
                SourceLine = 0,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                },
                MergeSources = new int[]
                {
                    3,
                    4
                },
                IsSynthetic = true,
                Invoke = static (__inputs, __ctx) => global::System.Threading.Tasks.Task.FromResult<object?>(null)
            };
            nodes[6] = new global::Raun.Model.ScenarioNode
            {
                Index = 6,
                StepId = "3a49d9ba399b77e3",
                Phase = "Then",
                OperationName = "AppointmentExists",
                DisplayNameTemplate = "the appointment should exist",
                SourceFile = "",
                SourceLine = 86,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0,
                    5
                },
                WaitsFor = new int[]
                {
                    3,
                    4
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    await __inputs.Get<global::Raun.ScenarioScope<global::Raun.NoWorld>>(0).Steps<global::CondDemo.CondThen>().AppointmentExists(__inputs.Get<global::CondDemo.Appointment>(5));
#line hidden
                    return (object? )null;
                }
            };
            nodes[7] = new global::Raun.Model.ScenarioNode
            {
                Index = 7,
                StepId = "825bb0992dba4429",
                Phase = "Then",
                OperationName = "Teardown",
                DisplayNameTemplate = "Teardown",
                SourceFile = null,
                SourceLine = 0,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                },
                IsTeardown = true,
                Invoke = static (__inputs, __ctx) => global::System.Threading.Tasks.Task.FromResult<object?>(null)
            };
            return new global::Raun.Model.ScenarioDefinition
            {
                ScenarioId = "28414318685d340d",
                DisplayName = "priority routing",
                MethodName = "CondDemo.IfElseScenarios.Routing",
                Namespace = "CondDemo",
                TypeName = "IfElseScenarios",
                ClassDisplayName = null,
                SourceFile = "",
                SourceLine = 76,
                Timeout = null,
                TeardownPolicy = (global::Raun.Run)0,
                Nodes = nodes,
                Method = typeof(global::CondDemo.IfElseScenarios).GetMethod("Routing", global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.DeclaredOnly)
            };
        }
    }
}
