//HintName: RaunScenarios.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
#line hidden
using Raun;
using System.Linq;
using System.Threading.Tasks;

namespace Raun.Generated
{
    internal static partial class RaunGenerated
    {
        public static global::System.Collections.Generic.IReadOnlyList<global::Raun.Model.ScenarioDefinition> CreateAll() => new global::Raun.Model.ScenarioDefinition[]
        {
            Scenario_Demo_BookingScenarios_Booking()
        };
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Initialize()
        {
            global::Raun.ScenarioRegistry.Register("Demo.BookingScenarios.Booking", Scenario_Demo_BookingScenarios_Booking);
        }
    }
}
