//HintName: RaunScenario.Demo_ArrayScenarios_Import.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
#line hidden
using Raun;
using System.Linq;
using System.Threading.Tasks;
using Demo;

namespace Raun.Generated
{
    internal static partial class RaunGenerated
    {
        public static global::Raun.Model.ScenarioDefinition Scenario_Demo_ArrayScenarios_Import()
        {
            var nodes = new global::Raun.Model.ScenarioNode[6];
            nodes[0] = new global::Raun.Model.ScenarioNode
            {
                Index = 0,
                StepId = "40b135563343034a",
                Phase = "Setup",
                OperationName = "Setup",
                DisplayNameTemplate = "Setup",
                SourceFile = null,
                SourceLine = 0,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                },
                IsSetup = true,
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await global::Raun.ScenarioScope.SetupAsync<global::Raun.NoWorld>(__ctx);
#line hidden
                    return (object? )__r;
                }
            };
            nodes[1] = new global::Raun.Model.ScenarioNode
            {
                Index = 1,
                StepId = "409989c70df28d22",
                Phase = "Given",
                OperationName = "UserExists",
                DisplayNameTemplate = "user alice exists",
                SourceFile = "",
                SourceLine = 82,
                GroupId = "g1",
                Timeout = null,
                DependsOn = new int[]
                {
                    0
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await __inputs.Get<global::Raun.ScenarioScope<global::Raun.NoWorld>>(0).Steps<global::Demo.AppointmentGiven>().UserExists("alice");
#line hidden
                    return (object? )__r;
                }
            };
            nodes[2] = new global::Raun.Model.ScenarioNode
            {
                Index = 2,
                StepId = "e3a937d2fe56991b",
                Phase = "Given",
                OperationName = "UserExists",
                DisplayNameTemplate = "user bob exists",
                SourceFile = "",
                SourceLine = 83,
                GroupId = "g1",
                Timeout = null,
                DependsOn = new int[]
                {
                    0
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await __inputs.Get<global::Raun.ScenarioScope<global::Raun.NoWorld>>(0).Steps<global::Demo.AppointmentGiven>().UserExists("bob");
#line hidden
                    return (object? )__r;
                }
            };
            nodes[3] = new global::Raun.Model.ScenarioNode
            {
                Index = 3,
                StepId = "e3d315bf20316dec",
                Phase = "When",
                OperationName = "ImportUsers",
                DisplayNameTemplate = "importing users",
                SourceFile = "",
                SourceLine = 86,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0,
                    1,
                    2
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await __inputs.Get<global::Raun.ScenarioScope<global::Raun.NoWorld>>(0).Steps<global::Demo.AppointmentWhen>().ImportUsers(new global::Demo.User[] { __inputs.Get<global::Demo.User>(1), __inputs.Get<global::Demo.User>(2) });
#line hidden
                    return (object? )__r;
                }
            };
            nodes[4] = new global::Raun.Model.ScenarioNode
            {
                Index = 4,
                StepId = "e54e734040605c4a",
                Phase = "Then",
                OperationName = "ImportShouldContainUsers",
                DisplayNameTemplate = "the import should contain the users",
                SourceFile = "",
                SourceLine = 87,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0,
                    1,
                    2,
                    3
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    await __inputs.Get<global::Raun.ScenarioScope<global::Raun.NoWorld>>(0).Steps<global::Demo.AppointmentThen>().ImportShouldContainUsers(__inputs.Get<global::Demo.Import>(3), new global::Demo.User[] { __inputs.Get<global::Demo.User>(1), __inputs.Get<global::Demo.User>(2) });
#line hidden
                    return (object? )null;
                }
            };
            nodes[5] = new global::Raun.Model.ScenarioNode
            {
                Index = 5,
                StepId = "afa7e3343e6dbe45",
                Phase = "Then",
                OperationName = "Teardown",
                DisplayNameTemplate = "Teardown",
                SourceFile = null,
                SourceLine = 0,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                },
                IsTeardown = true,
                Invoke = static (__inputs, __ctx) => global::System.Threading.Tasks.Task.FromResult<object?>(null)
            };
            return new global::Raun.Model.ScenarioDefinition
            {
                ScenarioId = "903e3e1cb803db83",
                DisplayName = "array import",
                MethodName = "Demo.ArrayScenarios.Import",
                Namespace = "Demo",
                TypeName = "ArrayScenarios",
                ClassDisplayName = null,
                SourceFile = "",
                SourceLine = 78,
                Timeout = null,
                TeardownPolicy = (global::Raun.Run)0,
                Nodes = nodes,
                Method = typeof(global::Demo.ArrayScenarios).GetMethod("Import", global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.DeclaredOnly)
            };
        }
    }
}
