//HintName: RaunScenarios.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
#line hidden
using Raun;
using System.Linq;
using System.Threading.Tasks;
using Demo;

namespace Raun.Generated
{
    internal static class RaunGenerated
    {
        public static global::System.Collections.Generic.IReadOnlyList<global::Raun.Model.ScenarioDefinition> CreateAll() => new global::Raun.Model.ScenarioDefinition[]
        {
            Scenario_Demo_GreetScenarios_Greeting()
        };
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Initialize()
        {
            global::Raun.ScenarioRegistry.Register("Demo.GreetScenarios.Greeting", Scenario_Demo_GreetScenarios_Greeting);
        }

        public static global::Raun.Model.ScenarioDefinition Scenario_Demo_GreetScenarios_Greeting()
        {
            var nodes = new global::Raun.Model.ScenarioNode[3];
            nodes[0] = new global::Raun.Model.ScenarioNode
            {
                Index = 0,
                StepId = "3751aece5ce6a3b0",
                Phase = "Given",
                OperationName = "PatientExists",
                DisplayNameTemplate = "patient Jane exists",
                SourceFile = "",
                SourceLine = 76,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await Given.PatientExists("Jane");
#line hidden
                    return (object? )__r;
                }
            };
            nodes[1] = new global::Raun.Model.ScenarioNode
            {
                Index = 1,
                StepId = "219555651c48ed47",
                Phase = "Then",
                OperationName = "Greet",
                DisplayNameTemplate = "greet {patient}",
                SourceFile = "",
                SourceLine = 77,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    await Then.Greet(__inputs.Get<global::Demo.Patient>(0));
#line hidden
                    return (object? )null;
                },
                FormatDisplayName = static __inputs => "greet " + (__inputs.Get<global::Demo.Patient>(0))
            };
            nodes[2] = new global::Raun.Model.ScenarioNode
            {
                Index = 2,
                StepId = "36dfbe9a7c09b96d",
                Phase = "Then",
                OperationName = "Teardown",
                DisplayNameTemplate = "Teardown",
                SourceFile = null,
                SourceLine = 0,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                },
                IsTeardown = true,
                Invoke = static (__inputs, __ctx) => global::System.Threading.Tasks.Task.FromResult<object?>(null)
            };
            return new global::Raun.Model.ScenarioDefinition
            {
                ScenarioId = "edc37eeb8a916c81",
                DisplayName = "greeting",
                MethodName = "Demo.GreetScenarios.Greeting",
                ClassDisplayName = null,
                SourceFile = "",
                SourceLine = 74,
                Timeout = null,
                TeardownPolicy = (global::Raun.Run)0,
                Nodes = nodes
            };
        }
    }
}
