//HintName: RaunScenario.ResourceDemo_ResourceScenarios_SuspendedUserCannotSignIn.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
#line hidden
using Raun;
using System.Linq;
using System.Threading.Tasks;
using ResourceDemo;

namespace Raun.Generated
{
    internal static partial class RaunGenerated
    {
        public static global::Raun.Model.ScenarioDefinition Scenario_ResourceDemo_ResourceScenarios_SuspendedUserCannotSignIn()
        {
            var nodes = new global::Raun.Model.ScenarioNode[5];
            nodes[0] = new global::Raun.Model.ScenarioNode
            {
                Index = 0,
                StepId = "e709f4664703302e",
                Phase = "Setup",
                OperationName = "Setup",
                DisplayNameTemplate = "Setup",
                SourceFile = null,
                SourceLine = 0,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                },
                IsSetup = true,
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await global::Raun.ScenarioScope.SetupAsync<global::Raun.NoWorld>(__ctx);
#line hidden
                    return (object? )__r;
                }
            };
            nodes[1] = new global::Raun.Model.ScenarioNode
            {
                Index = 1,
                StepId = "915feb2d989ce6e1",
                Phase = "Given",
                OperationName = "UserExists",
                DisplayNameTemplate = "user jane@acme.com exists",
                SourceFile = "",
                SourceLine = 84,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await __inputs.Get<global::Raun.ScenarioScope<global::Raun.NoWorld>>(0).Steps<global::ResourceDemo.ResourceGiven>().UserExists("jane@acme.com");
#line hidden
                    await __ctx.Resources.Create(__r);
#line hidden
                    return (object? )__r;
                }
            };
            nodes[2] = new global::Raun.Model.ScenarioNode
            {
                Index = 2,
                StepId = "4ffb9a58c73ac0cc",
                Phase = "When",
                OperationName = "Suspend",
                DisplayNameTemplate = "suspending the user",
                SourceFile = "",
                SourceLine = 85,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0,
                    1
                },
                Invoke = static async (__inputs, __ctx) =>
                {
#line hidden
                    await __ctx.Resources.Edit(__inputs.Get<global::ResourceDemo.User>(1));
                    var __r = await __inputs.Get<global::Raun.ScenarioScope<global::Raun.NoWorld>>(0).Steps<global::ResourceDemo.ResourceWhen>().Suspend(__inputs.Get<global::ResourceDemo.User>(1));
#line hidden
                    await __ctx.Resources.Edit(__r);
#line hidden
                    return (object? )__r;
                }
            };
            nodes[3] = new global::Raun.Model.ScenarioNode
            {
                Index = 3,
                StepId = "d9e8bf4da464fe19",
                Phase = "Then",
                OperationName = "CannotSignIn",
                DisplayNameTemplate = "the user cannot sign in",
                SourceFile = "",
                SourceLine = 86,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0,
                    2
                },
                Invoke = static async (__inputs, __ctx) =>
                {
#line hidden
                    await __ctx.Resources.Read(__inputs.Get<global::ResourceDemo.User>(2));
                    await __inputs.Get<global::Raun.ScenarioScope<global::Raun.NoWorld>>(0).Steps<global::ResourceDemo.ResourceThen>().CannotSignIn(__inputs.Get<global::ResourceDemo.User>(2));
#line hidden
                    return (object? )null;
                }
            };
            nodes[4] = new global::Raun.Model.ScenarioNode
            {
                Index = 4,
                StepId = "d4612f2bbb9e7e99",
                Phase = "Then",
                OperationName = "Teardown",
                DisplayNameTemplate = "Teardown",
                SourceFile = null,
                SourceLine = 0,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                },
                IsTeardown = true,
                Invoke = static (__inputs, __ctx) => global::System.Threading.Tasks.Task.FromResult<object?>(null)
            };
            return new global::Raun.Model.ScenarioDefinition
            {
                ScenarioId = "c01f329e4fc6cd1a",
                DisplayName = "suspended user cannot sign in",
                MethodName = "ResourceDemo.ResourceScenarios.SuspendedUserCannotSignIn",
                Namespace = "ResourceDemo",
                TypeName = "ResourceScenarios",
                ClassDisplayName = null,
                SourceFile = "",
                SourceLine = 82,
                Timeout = null,
                TeardownPolicy = (global::Raun.Run)0,
                Nodes = nodes,
                Method = typeof(global::ResourceDemo.ResourceScenarios).GetMethod("SuspendedUserCannotSignIn", global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.DeclaredOnly)
            };
        }
    }
}
