//HintName: RaunScenarios.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
#line hidden
using Raun;
using System.Linq;
using System.Threading.Tasks;
using UsesDemo;

namespace Raun.Generated
{
    internal static class RaunGenerated
    {
        public static global::System.Collections.Generic.IReadOnlyList<global::Raun.Model.ScenarioDefinition> CreateAll() => new global::Raun.Model.ScenarioDefinition[]
        {
            Scenario_UsesDemo_UsesScenarios_ClearAndRemind()
        };
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Initialize()
        {
            global::Raun.ScenarioRegistry.Register("UsesDemo.UsesScenarios.ClearAndRemind", Scenario_UsesDemo_UsesScenarios_ClearAndRemind);
        }

        public static global::Raun.Model.ScenarioDefinition Scenario_UsesDemo_UsesScenarios_ClearAndRemind()
        {
            var nodes = new global::Raun.Model.ScenarioNode[3];
            nodes[0] = new global::Raun.Model.ScenarioNode
            {
                Index = 0,
                StepId = "41f859d4ba1039aa",
                Phase = "Given",
                OperationName = "ScheduleIsEmpty",
                DisplayNameTemplate = "the schedule is empty",
                SourceFile = "",
                SourceLine = 43,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    await Given.ScheduleIsEmpty();
#line hidden
                    return (object? )null;
                }
            };
            nodes[1] = new global::Raun.Model.ScenarioNode
            {
                Index = 1,
                StepId = "dcdd1698f574d30b",
                Phase = "When",
                OperationName = "ReminderIsSent",
                DisplayNameTemplate = "a reminder is sent",
                SourceFile = "",
                SourceLine = 44,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    await When.ReminderIsSent();
#line hidden
                    return (object? )null;
                }
            };
            nodes[2] = new global::Raun.Model.ScenarioNode
            {
                Index = 2,
                StepId = "1d1c94720a888a0a",
                Phase = "Then",
                OperationName = "Teardown",
                DisplayNameTemplate = "Teardown",
                SourceFile = null,
                SourceLine = 0,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                },
                IsTeardown = true,
                Invoke = static (__inputs, __ctx) => global::System.Threading.Tasks.Task.FromResult<object?>(null)
            };
            return new global::Raun.Model.ScenarioDefinition
            {
                ScenarioId = "df09c8dfa69bf244",
                DisplayName = "clears and reminds",
                MethodName = "UsesDemo.UsesScenarios.ClearAndRemind",
                ClassDisplayName = null,
                SourceFile = "",
                SourceLine = 41,
                Timeout = null,
                TeardownPolicy = (global::Raun.Run)0,
                Nodes = nodes,
                Uses = new global::Raun.ContendedResourceUse[]
                {
                    new global::Raun.ContendedResourceUse(typeof(global::UsesDemo.Audit), global::Raun.LockMode.Shared),
                    new global::Raun.ContendedResourceUse(typeof(global::UsesDemo.Database), global::Raun.LockMode.Exclusive),
                    new global::Raun.ContendedResourceUse(typeof(global::UsesDemo.Smtp), global::Raun.LockMode.Shared)
                }
            };
        }
    }
}
