//HintName: RaunScenarios.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
#line hidden
using Raun;
using System.Linq;
using System.Threading.Tasks;

namespace Raun.Generated
{
    internal static partial class RaunGenerated
    {
        public static global::System.Collections.Generic.IReadOnlyList<global::Raun.Model.ScenarioDefinition> CreateAll() => new global::Raun.Model.ScenarioDefinition[]
        {
            Scenario_ResourceDemo_ResourceScenarios_SuspendedUserCannotSignIn()
        };
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Initialize()
        {
            global::Raun.ScenarioRegistry.Register("ResourceDemo.ResourceScenarios.SuspendedUserCannotSignIn", Scenario_ResourceDemo_ResourceScenarios_SuspendedUserCannotSignIn);
        }
    }
}
