//HintName: RaunScenario.OutcomeDemo_SwitchScenarios_Route.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
#line hidden
using Raun;
using System.Linq;
using System.Threading.Tasks;
using OutcomeDemo;

namespace Raun.Generated
{
    internal static partial class RaunGenerated
    {
        public static global::Raun.Model.ScenarioDefinition Scenario_OutcomeDemo_SwitchScenarios_Route()
        {
            var nodes = new global::Raun.Model.ScenarioNode[10];
            nodes[0] = new global::Raun.Model.ScenarioNode
            {
                Index = 0,
                StepId = "a4d3f75dff91009b",
                Phase = "Setup",
                OperationName = "Setup",
                DisplayNameTemplate = "Setup",
                SourceFile = null,
                SourceLine = 0,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                },
                IsSetup = true,
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await global::Raun.ScenarioScope.SetupAsync<global::Raun.NoWorld>(__ctx);
#line hidden
                    return (object? )__r;
                }
            };
            nodes[1] = new global::Raun.Model.ScenarioNode
            {
                Index = 1,
                StepId = "2893a053dd11ab7c",
                Phase = "When",
                OperationName = "Submit",
                DisplayNameTemplate = "submitting order big",
                SourceFile = "",
                SourceLine = 67,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0
                },
                SelectArm = static __inputs =>
                {
                    switch (__inputs.Get<global::OutcomeDemo.Outcome>(1))
                    {
                        case global::OutcomeDemo.Accepted { Total: > 1000 } big:
                            return 0;
                        case global::OutcomeDemo.Accepted accepted when accepted.Express:
                            return 1;
                        case global::OutcomeDemo.Rejected rejected:
                            return 2;
                        default:
                            return 3;
                    }
                },
                Arms = new string[]
                {
                    "case Accepted { Total: > 1000 } big",
                    "case Accepted accepted when accepted.Express",
                    "case Rejected rejected",
                    "default"
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await __inputs.Get<global::Raun.ScenarioScope<global::Raun.NoWorld>>(0).Steps<global::OutcomeDemo.OutcomeWhen>().Submit("big");
#line hidden
                    return (object? )__r;
                }
            };
            nodes[2] = new global::Raun.Model.ScenarioNode
            {
                Index = 2,
                StepId = "ab7b85eed3926419",
                Phase = "When",
                OperationName = "Case",
                DisplayNameTemplate = "«case Accepted { Total: > 1000 } big»",
                SourceFile = null,
                SourceLine = 0,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    1
                },
                Guards = new global::Raun.Model.Guard[]
                {
                    new global::Raun.Model.Guard(1, 0)
                },
                IsSynthetic = true,
                Invoke = static (__inputs, __ctx) =>
                {
                    var __v = __inputs.Get<global::OutcomeDemo.Outcome>(1);
                    if (__v is global::OutcomeDemo.Accepted { Total: > 1000 } big)
                        return global::System.Threading.Tasks.Task.FromResult<object?>(big);
                    throw new global::System.InvalidOperationException("A case node ran but its arm's pattern did not match; this is a Raun generator bug.");
                }
            };
            nodes[3] = new global::Raun.Model.ScenarioNode
            {
                Index = 3,
                StepId = "7e50efd5f5609d08",
                Phase = "Then",
                OperationName = "Review",
                DisplayNameTemplate = "review of {total:0.00}",
                SourceFile = "",
                SourceLine = 70,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0,
                    1,
                    2
                },
                Guards = new global::Raun.Model.Guard[]
                {
                    new global::Raun.Model.Guard(1, 0)
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    await __inputs.Get<global::Raun.ScenarioScope<global::Raun.NoWorld>>(0).Steps<global::OutcomeDemo.OutcomeThen>().Review(__inputs.Get<global::OutcomeDemo.Accepted>(2).Total);
#line hidden
                    return (object? )null;
                },
                FormatDisplayName = static __inputs => "review of " + ((global::System.IFormattable? )((__inputs.Get<global::OutcomeDemo.Accepted>(2).Total)))?.ToString("0.00", global::System.Globalization.CultureInfo.InvariantCulture)
            };
            nodes[4] = new global::Raun.Model.ScenarioNode
            {
                Index = 4,
                StepId = "ab7b84eed3926266",
                Phase = "When",
                OperationName = "Case",
                DisplayNameTemplate = "«case Accepted accepted when accepted.Express»",
                SourceFile = null,
                SourceLine = 0,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    1
                },
                Guards = new global::Raun.Model.Guard[]
                {
                    new global::Raun.Model.Guard(1, 1)
                },
                IsSynthetic = true,
                Invoke = static (__inputs, __ctx) =>
                {
                    var __v = __inputs.Get<global::OutcomeDemo.Outcome>(1);
                    if (__v is global::OutcomeDemo.Accepted accepted)
                        return global::System.Threading.Tasks.Task.FromResult<object?>(accepted);
                    throw new global::System.InvalidOperationException("A case node ran but its arm's pattern did not match; this is a Raun generator bug.");
                }
            };
            nodes[5] = new global::Raun.Model.ScenarioNode
            {
                Index = 5,
                StepId = "f744d1a79b4aec30",
                Phase = "Then",
                OperationName = "Shipped",
                DisplayNameTemplate = "shipment {shipment} scheduled",
                SourceFile = "",
                SourceLine = 73,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0,
                    1,
                    4
                },
                Guards = new global::Raun.Model.Guard[]
                {
                    new global::Raun.Model.Guard(1, 1)
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    await __inputs.Get<global::Raun.ScenarioScope<global::Raun.NoWorld>>(0).Steps<global::OutcomeDemo.OutcomeThen>().Shipped(__inputs.Get<global::OutcomeDemo.Accepted>(4).Shipment);
#line hidden
                    return (object? )null;
                },
                FormatDisplayName = static __inputs => "shipment " + (__inputs.Get<global::OutcomeDemo.Accepted>(4).Shipment) + " scheduled"
            };
            nodes[6] = new global::Raun.Model.ScenarioNode
            {
                Index = 6,
                StepId = "ab7b83eed39260b3",
                Phase = "When",
                OperationName = "Case",
                DisplayNameTemplate = "«case Rejected rejected»",
                SourceFile = null,
                SourceLine = 0,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    1
                },
                Guards = new global::Raun.Model.Guard[]
                {
                    new global::Raun.Model.Guard(1, 2)
                },
                IsSynthetic = true,
                Invoke = static (__inputs, __ctx) =>
                {
                    var __v = __inputs.Get<global::OutcomeDemo.Outcome>(1);
                    if (__v is global::OutcomeDemo.Rejected rejected)
                        return global::System.Threading.Tasks.Task.FromResult<object?>(rejected);
                    throw new global::System.InvalidOperationException("A case node ran but its arm's pattern did not match; this is a Raun generator bug.");
                }
            };
            nodes[7] = new global::Raun.Model.ScenarioNode
            {
                Index = 7,
                StepId = "c4979ad6d400b1b9",
                Phase = "Then",
                OperationName = "Told",
                DisplayNameTemplate = "customer told {reason}",
                SourceFile = "",
                SourceLine = 76,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0,
                    1,
                    6
                },
                Guards = new global::Raun.Model.Guard[]
                {
                    new global::Raun.Model.Guard(1, 2)
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    await __inputs.Get<global::Raun.ScenarioScope<global::Raun.NoWorld>>(0).Steps<global::OutcomeDemo.OutcomeThen>().Told(__inputs.Get<global::OutcomeDemo.Rejected>(6).Reason);
#line hidden
                    return (object? )null;
                },
                FormatDisplayName = static __inputs => "customer told " + (__inputs.Get<global::OutcomeDemo.Rejected>(6).Reason)
            };
            nodes[8] = new global::Raun.Model.ScenarioNode
            {
                Index = 8,
                StepId = "3a4feaf61576b06f",
                Phase = "Then",
                OperationName = "StillPending",
                DisplayNameTemplate = "order pending",
                SourceFile = "",
                SourceLine = 79,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0,
                    1
                },
                Guards = new global::Raun.Model.Guard[]
                {
                    new global::Raun.Model.Guard(1, 3)
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    await __inputs.Get<global::Raun.ScenarioScope<global::Raun.NoWorld>>(0).Steps<global::OutcomeDemo.OutcomeThen>().StillPending();
#line hidden
                    return (object? )null;
                }
            };
            nodes[9] = new global::Raun.Model.ScenarioNode
            {
                Index = 9,
                StepId = "35522d794e52815e",
                Phase = "Then",
                OperationName = "Teardown",
                DisplayNameTemplate = "Teardown",
                SourceFile = null,
                SourceLine = 0,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                },
                IsTeardown = true,
                Invoke = static (__inputs, __ctx) => global::System.Threading.Tasks.Task.FromResult<object?>(null)
            };
            return new global::Raun.Model.ScenarioDefinition
            {
                ScenarioId = "6c9e9e6bb1e84706",
                DisplayName = "an order is routed by its outcome",
                MethodName = "OutcomeDemo.SwitchScenarios.Route",
                Namespace = "OutcomeDemo",
                TypeName = "SwitchScenarios",
                ClassDisplayName = null,
                SourceFile = "",
                SourceLine = 65,
                Timeout = null,
                TeardownPolicy = (global::Raun.Run)0,
                Nodes = nodes,
                Method = typeof(global::OutcomeDemo.SwitchScenarios).GetMethod("Route", global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.DeclaredOnly)
            };
        }
    }
}
