//HintName: RaunScenarios.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
#line hidden
using Raun;
using System.Linq;
using System.Threading.Tasks;
using Demo;

namespace Raun.Generated
{
    internal static class RaunGenerated
    {
        public static global::System.Collections.Generic.IReadOnlyList<global::Raun.Model.ScenarioDefinition> CreateAll() => new global::Raun.Model.ScenarioDefinition[]
        {
            Scenario_Demo_BookingScenarios_Booking()
        };
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Initialize()
        {
            global::Raun.ScenarioRegistry.Register("Demo.BookingScenarios.Booking", Scenario_Demo_BookingScenarios_Booking);
        }

        public static global::Raun.Model.ScenarioDefinition Scenario_Demo_BookingScenarios_Booking()
        {
            var nodes = new global::Raun.Model.ScenarioNode[5];
            nodes[0] = new global::Raun.Model.ScenarioNode
            {
                Index = 0,
                StepId = "fc427b5685e22f40",
                Phase = "Given",
                OperationName = "PatientExists",
                DisplayNameTemplate = "patient Jane exists",
                SourceFile = "",
                SourceLine = 76,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await Given.PatientExists("Jane");
#line hidden
                    return (object? )__r;
                }
            };
            nodes[1] = new global::Raun.Model.ScenarioNode
            {
                Index = 1,
                StepId = "bddc40ffb5cfd92d",
                Phase = "Given",
                OperationName = "AvailableSlot",
                DisplayNameTemplate = "an available slot exists",
                SourceFile = "",
                SourceLine = 77,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await Given.AvailableSlot();
#line hidden
                    return (object? )__r;
                }
            };
            nodes[2] = new global::Raun.Model.ScenarioNode
            {
                Index = 2,
                StepId = "13d67006c7f190e2",
                Phase = "When",
                OperationName = "CreateAppointment",
                DisplayNameTemplate = "creating an appointment",
                SourceFile = "",
                SourceLine = 78,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0,
                    1
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await When.CreateAppointment(__inputs.Get<global::Demo.Patient>(0), __inputs.Get<global::Demo.Slot>(1));
#line hidden
                    return (object? )__r;
                }
            };
            nodes[3] = new global::Raun.Model.ScenarioNode
            {
                Index = 3,
                StepId = "629f5e6bf5f7fafd",
                Phase = "Then",
                OperationName = "AppointmentExists",
                DisplayNameTemplate = "the appointment should exist",
                SourceFile = "",
                SourceLine = 79,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    2
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    await Then.AppointmentExists(__inputs.Get<global::Demo.Appointment>(2));
#line hidden
                    return (object? )null;
                }
            };
            nodes[4] = new global::Raun.Model.ScenarioNode
            {
                Index = 4,
                StepId = "47d7b0d2df24045d",
                Phase = "Then",
                OperationName = "Teardown",
                DisplayNameTemplate = "Teardown",
                SourceFile = null,
                SourceLine = 0,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                },
                IsTeardown = true,
                Invoke = static (__inputs, __ctx) => global::System.Threading.Tasks.Task.FromResult<object?>(null)
            };
            return new global::Raun.Model.ScenarioDefinition
            {
                ScenarioId = "3907d8692f8a5dab",
                DisplayName = "booking",
                MethodName = "Demo.BookingScenarios.Booking",
                Namespace = "Demo",
                TypeName = "BookingScenarios",
                ClassDisplayName = null,
                SourceFile = "",
                SourceLine = 74,
                Timeout = null,
                TeardownPolicy = (global::Raun.Run)0,
                Nodes = nodes
            };
        }
    }
}
