//HintName: RaunScenario.Clinic_CancellationScenarios_CustomerCancels.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
#line hidden
using Raun;
using System.Linq;
using System.Threading.Tasks;
using System;
using System.Collections.Concurrent;
using System.Reflection;
using System.Threading;
using Clinic;

namespace Raun.Generated
{
    internal static partial class RaunGenerated
    {
        public static global::Raun.Model.ScenarioDefinition Scenario_Clinic_CancellationScenarios_CustomerCancels()
        {
            var nodes = new global::Raun.Model.ScenarioNode[11];
            nodes[0] = new global::Raun.Model.ScenarioNode
            {
                Index = 0,
                StepId = "ae0cc9dc4ffa4593",
                Phase = "Setup",
                OperationName = "Setup",
                DisplayNameTemplate = "Setup",
                SourceFile = null,
                SourceLine = 0,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                },
                IsSetup = true,
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await global::Raun.ScenarioScope.SetupAsync<global::Clinic.ClinicWorld>(__ctx);
#line hidden
                    return (object? )__r;
                }
            };
            nodes[1] = new global::Raun.Model.ScenarioNode
            {
                Index = 1,
                StepId = "24883e4ed7eabddb",
                Phase = "Given",
                OperationName = "Exists",
                DisplayNameTemplate = "customer Jane exists",
                SourceFile = "",
                SourceLine = 181,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await __inputs.Get<global::Raun.ScenarioScope<global::Clinic.ClinicWorld>>(0).Steps<global::Clinic.CustomerSteps>().Exists("Jane");
#line hidden
                    return (object? )__r;
                }
            };
            nodes[2] = new global::Raun.Model.ScenarioNode
            {
                Index = 2,
                StepId = "1d1410dc447d8ea3",
                Phase = "Given",
                OperationName = "Existing",
                DisplayNameTemplate = "{customer} has an appointment",
                SourceFile = "",
                SourceLine = 182,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0,
                    1
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await __inputs.Get<global::Raun.ScenarioScope<global::Clinic.ClinicWorld>>(0).Steps<global::Clinic.ExistingAppointments>().Existing(__inputs.Get<global::Clinic.Customer>(1));
#line hidden
                    return (object? )__r;
                },
                FormatDisplayName = static __inputs => "" + (__inputs.Get<global::Clinic.Customer>(1)) + " has an appointment"
            };
            nodes[3] = new global::Raun.Model.ScenarioNode
            {
                Index = 3,
                StepId = "1643d0335ce9932d",
                Phase = "Given",
                OperationName = "Accepts",
                DisplayNameTemplate = "the notification stub accepts",
                SourceFile = "",
                SourceLine = 183,
                GroupId = "g3",
                Timeout = null,
                DependsOn = new int[]
                {
                    0,
                    2
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    await __inputs.Get<global::Raun.ScenarioScope<global::Clinic.ClinicWorld>>(0).Steps<global::Clinic.StubSteps>().Accepts("notification");
#line hidden
                    return (object? )null;
                }
            };
            nodes[4] = new global::Raun.Model.ScenarioNode
            {
                Index = 4,
                StepId = "ef04c3062bafca4e",
                Phase = "Given",
                OperationName = "Accepts",
                DisplayNameTemplate = "the calendar stub accepts",
                SourceFile = "",
                SourceLine = 183,
                GroupId = "g3",
                Timeout = null,
                DependsOn = new int[]
                {
                    0,
                    2
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    await __inputs.Get<global::Raun.ScenarioScope<global::Clinic.ClinicWorld>>(0).Steps<global::Clinic.StubSteps>().Accepts("calendar");
#line hidden
                    return (object? )null;
                }
            };
            nodes[5] = new global::Raun.Model.ScenarioNode
            {
                Index = 5,
                StepId = "590bfacb62ca5839",
                Phase = "When",
                OperationName = "Cancel",
                DisplayNameTemplate = "{customer} cancels {appointment}",
                SourceFile = "",
                SourceLine = 184,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0,
                    1,
                    2,
                    3,
                    4
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await __inputs.Get<global::Raun.ScenarioScope<global::Clinic.ClinicWorld>>(0).Steps<global::Clinic.AppointmentActions>().Cancel(__inputs.Get<global::Clinic.Customer>(1), __inputs.Get<global::Clinic.Appointment>(2));
#line hidden
                    return (object? )__r;
                },
                FormatDisplayName = static __inputs => "" + (__inputs.Get<global::Clinic.Customer>(1)) + " cancels " + (__inputs.Get<global::Clinic.Appointment>(2))
            };
            nodes[6] = new global::Raun.Model.ScenarioNode
            {
                Index = 6,
                StepId = "52a2c6576a8b17c8",
                Phase = "Then",
                OperationName = "IsCancelled",
                DisplayNameTemplate = "{appointment} is cancelled",
                SourceFile = "",
                SourceLine = 185,
                GroupId = "g6",
                Timeout = null,
                DependsOn = new int[]
                {
                    0,
                    5
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    await __inputs.Get<global::Raun.ScenarioScope<global::Clinic.ClinicWorld>>(0).Steps<global::Clinic.ClinicThen>().IsCancelled(__inputs.Get<global::Clinic.Appointment>(5));
#line hidden
                    return (object? )null;
                },
                FormatDisplayName = static __inputs => "" + (__inputs.Get<global::Clinic.Appointment>(5)) + " is cancelled"
            };
            nodes[7] = new global::Raun.Model.ScenarioNode
            {
                Index = 7,
                StepId = "3ac07ac44c134f69",
                Phase = "Then",
                OperationName = "StubWasSetUp",
                DisplayNameTemplate = "the notification stub was set up",
                SourceFile = "",
                SourceLine = 185,
                GroupId = "g6",
                Timeout = null,
                DependsOn = new int[]
                {
                    0,
                    5
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    await __inputs.Get<global::Raun.ScenarioScope<global::Clinic.ClinicWorld>>(0).Steps<global::Clinic.ClinicThen>().StubWasSetUp("notification");
#line hidden
                    return (object? )null;
                }
            };
            nodes[8] = new global::Raun.Model.ScenarioNode
            {
                Index = 8,
                StepId = "f9d8671105071d52",
                Phase = "Then",
                OperationName = "StubWasSetUp",
                DisplayNameTemplate = "the calendar stub was set up",
                SourceFile = "",
                SourceLine = 185,
                GroupId = "g6",
                Timeout = null,
                DependsOn = new int[]
                {
                    0,
                    5
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    await __inputs.Get<global::Raun.ScenarioScope<global::Clinic.ClinicWorld>>(0).Steps<global::Clinic.ClinicThen>().StubWasSetUp("calendar");
#line hidden
                    return (object? )null;
                }
            };
            nodes[9] = new global::Raun.Model.ScenarioNode
            {
                Index = 9,
                StepId = "1a6c07e9188041b6",
                Phase = "Eventually",
                OperationName = "CalendarIsFree",
                DisplayNameTemplate = "the calendar is free for {customer}",
                SourceFile = "",
                SourceLine = 186,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0,
                    1,
                    6,
                    7,
                    8
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    await __inputs.Get<global::Raun.ScenarioScope<global::Clinic.ClinicWorld>>(0).Steps<global::Clinic.ClinicEventually>().CalendarIsFree(__inputs.Get<global::Clinic.Customer>(1));
#line hidden
                    return (object? )null;
                },
                FormatDisplayName = static __inputs => "the calendar is free for " + (__inputs.Get<global::Clinic.Customer>(1))
            };
            nodes[10] = new global::Raun.Model.ScenarioNode
            {
                Index = 10,
                StepId = "73974e40f4edacc6",
                Phase = "Then",
                OperationName = "Teardown",
                DisplayNameTemplate = "Teardown",
                SourceFile = null,
                SourceLine = 0,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                },
                IsTeardown = true,
                Invoke = static (__inputs, __ctx) => global::System.Threading.Tasks.Task.FromResult<object?>(null)
            };
            return new global::Raun.Model.ScenarioDefinition
            {
                ScenarioId = "573771e34c9d612c",
                DisplayName = "customer cancels an appointment",
                MethodName = "Clinic.CancellationScenarios.CustomerCancels",
                Namespace = "Clinic",
                TypeName = "CancellationScenarios",
                ClassDisplayName = null,
                SourceFile = "",
                SourceLine = 179,
                Timeout = null,
                TeardownPolicy = (global::Raun.Run)0,
                Nodes = nodes,
                Method = typeof(global::Clinic.CancellationScenarios).GetMethod("CustomerCancels", global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.DeclaredOnly)
            };
        }
    }
}
