//HintName: RaunScenario.Demo_BookingScenarios_Booking.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
#line hidden
using Raun;
using System.Linq;
using System.Threading.Tasks;
using Demo;

namespace Raun.Generated
{
    internal static partial class RaunGenerated
    {
        public static global::Raun.Model.ScenarioDefinition Scenario_Demo_BookingScenarios_Booking()
        {
            var nodes = new global::Raun.Model.ScenarioNode[6];
            nodes[0] = new global::Raun.Model.ScenarioNode
            {
                Index = 0,
                StepId = "8f8503554813bf12",
                Phase = "Setup",
                OperationName = "Setup",
                DisplayNameTemplate = "Setup",
                SourceFile = null,
                SourceLine = 0,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                },
                IsSetup = true,
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await global::Raun.ScenarioScope.SetupAsync<global::Raun.NoWorld>(__ctx);
#line hidden
                    return (object? )__r;
                }
            };
            nodes[1] = new global::Raun.Model.ScenarioNode
            {
                Index = 1,
                StepId = "ea42275a0641a48a",
                Phase = "Given",
                OperationName = "PatientExists",
                DisplayNameTemplate = "patient Jane exists",
                SourceFile = "",
                SourceLine = 80,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await __inputs.Get<global::Raun.ScenarioScope<global::Raun.NoWorld>>(0).Steps<global::Demo.AppointmentGiven>().PatientExists("Jane");
#line hidden
                    return (object? )__r;
                }
            };
            nodes[2] = new global::Raun.Model.ScenarioNode
            {
                Index = 2,
                StepId = "d4be74fa4d9b083c",
                Phase = "Given",
                OperationName = "AvailableSlot",
                DisplayNameTemplate = "an available slot exists",
                SourceFile = "",
                SourceLine = 81,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0,
                    1
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await __inputs.Get<global::Raun.ScenarioScope<global::Raun.NoWorld>>(0).Steps<global::Demo.AppointmentGiven>().AvailableSlot();
#line hidden
                    return (object? )__r;
                }
            };
            nodes[3] = new global::Raun.Model.ScenarioNode
            {
                Index = 3,
                StepId = "958b21bfb2637d55",
                Phase = "When",
                OperationName = "CreateAppointment",
                DisplayNameTemplate = "creating an appointment",
                SourceFile = "",
                SourceLine = 82,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0,
                    1,
                    2
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await __inputs.Get<global::Raun.ScenarioScope<global::Raun.NoWorld>>(0).Steps<global::Demo.AppointmentWhen>().CreateAppointment(__inputs.Get<global::Demo.Patient>(1), __inputs.Get<global::Demo.Slot>(2));
#line hidden
                    return (object? )__r;
                }
            };
            nodes[4] = new global::Raun.Model.ScenarioNode
            {
                Index = 4,
                StepId = "d17b72cf7d550047",
                Phase = "Then",
                OperationName = "AppointmentExists",
                DisplayNameTemplate = "the appointment should exist",
                SourceFile = "",
                SourceLine = 83,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0,
                    3
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    await __inputs.Get<global::Raun.ScenarioScope<global::Raun.NoWorld>>(0).Steps<global::Demo.AppointmentThen>().AppointmentExists(__inputs.Get<global::Demo.Appointment>(3));
#line hidden
                    return (object? )null;
                }
            };
            nodes[5] = new global::Raun.Model.ScenarioNode
            {
                Index = 5,
                StepId = "47d7b0d2df24045d",
                Phase = "Then",
                OperationName = "Teardown",
                DisplayNameTemplate = "Teardown",
                SourceFile = null,
                SourceLine = 0,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                },
                IsTeardown = true,
                Invoke = static (__inputs, __ctx) => global::System.Threading.Tasks.Task.FromResult<object?>(null)
            };
            return new global::Raun.Model.ScenarioDefinition
            {
                ScenarioId = "3907d8692f8a5dab",
                DisplayName = "booking",
                MethodName = "Demo.BookingScenarios.Booking",
                Namespace = "Demo",
                TypeName = "BookingScenarios",
                ClassDisplayName = null,
                SourceFile = "",
                SourceLine = 78,
                Timeout = null,
                TeardownPolicy = (global::Raun.Run)0,
                Nodes = nodes,
                Method = typeof(global::Demo.BookingScenarios).GetMethod("Booking", global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.DeclaredOnly)
            };
        }
    }
}
