//HintName: RaunScenario.Demo_TupleScenarios_Booking.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
#line hidden
using Raun;
using System.Linq;
using System.Threading.Tasks;
using Demo;

namespace Raun.Generated
{
    internal static partial class RaunGenerated
    {
        public static global::Raun.Model.ScenarioDefinition Scenario_Demo_TupleScenarios_Booking()
        {
            var nodes = new global::Raun.Model.ScenarioNode[7];
            nodes[0] = new global::Raun.Model.ScenarioNode
            {
                Index = 0,
                StepId = "308b6e718dbba42a",
                Phase = "Setup",
                OperationName = "Setup",
                DisplayNameTemplate = "Setup",
                SourceFile = null,
                SourceLine = 0,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                },
                IsSetup = true,
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await global::Raun.ScenarioScope.SetupAsync<global::Raun.NoWorld>(__ctx);
#line hidden
                    return (object? )__r;
                }
            };
            nodes[1] = new global::Raun.Model.ScenarioNode
            {
                Index = 1,
                StepId = "4a65e0dd847eba1d",
                Phase = "Given",
                OperationName = "DatabaseIsClean",
                DisplayNameTemplate = "database is clean",
                SourceFile = "",
                SourceLine = 80,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    await __inputs.Get<global::Raun.ScenarioScope<global::Raun.NoWorld>>(0).Steps<global::Demo.AppointmentGiven>().DatabaseIsClean();
#line hidden
                    return (object? )null;
                }
            };
            nodes[2] = new global::Raun.Model.ScenarioNode
            {
                Index = 2,
                StepId = "8261dc3d1d612fd2",
                Phase = "Given",
                OperationName = "PatientExists",
                DisplayNameTemplate = "patient Jane exists",
                SourceFile = "",
                SourceLine = 83,
                GroupId = "g2",
                Timeout = null,
                DependsOn = new int[]
                {
                    0,
                    1
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await __inputs.Get<global::Raun.ScenarioScope<global::Raun.NoWorld>>(0).Steps<global::Demo.AppointmentGiven>().PatientExists("Jane");
#line hidden
                    return (object? )__r;
                }
            };
            nodes[3] = new global::Raun.Model.ScenarioNode
            {
                Index = 3,
                StepId = "8d88cd5be5717294",
                Phase = "Given",
                OperationName = "AvailableSlot",
                DisplayNameTemplate = "an available slot exists",
                SourceFile = "",
                SourceLine = 84,
                GroupId = "g2",
                Timeout = null,
                DependsOn = new int[]
                {
                    0,
                    1
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await __inputs.Get<global::Raun.ScenarioScope<global::Raun.NoWorld>>(0).Steps<global::Demo.AppointmentGiven>().AvailableSlot();
#line hidden
                    return (object? )__r;
                }
            };
            nodes[4] = new global::Raun.Model.ScenarioNode
            {
                Index = 4,
                StepId = "184e26fde1be711d",
                Phase = "When",
                OperationName = "CreateAppointment",
                DisplayNameTemplate = "creating an appointment",
                SourceFile = "",
                SourceLine = 86,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0,
                    2,
                    3
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await __inputs.Get<global::Raun.ScenarioScope<global::Raun.NoWorld>>(0).Steps<global::Demo.AppointmentWhen>().CreateAppointment(__inputs.Get<global::Demo.Patient>(2), __inputs.Get<global::Demo.Slot>(3));
#line hidden
                    return (object? )__r;
                }
            };
            nodes[5] = new global::Raun.Model.ScenarioNode
            {
                Index = 5,
                StepId = "fef2f599745c519f",
                Phase = "Then",
                OperationName = "AppointmentExists",
                DisplayNameTemplate = "the appointment should exist",
                SourceFile = "",
                SourceLine = 87,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0,
                    4
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    await __inputs.Get<global::Raun.ScenarioScope<global::Raun.NoWorld>>(0).Steps<global::Demo.AppointmentThen>().AppointmentExists(__inputs.Get<global::Demo.Appointment>(4));
#line hidden
                    return (object? )null;
                }
            };
            nodes[6] = new global::Raun.Model.ScenarioNode
            {
                Index = 6,
                StepId = "b491d19b417855a5",
                Phase = "Then",
                OperationName = "Teardown",
                DisplayNameTemplate = "Teardown",
                SourceFile = null,
                SourceLine = 0,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                },
                IsTeardown = true,
                Invoke = static (__inputs, __ctx) => global::System.Threading.Tasks.Task.FromResult<object?>(null)
            };
            return new global::Raun.Model.ScenarioDefinition
            {
                ScenarioId = "c437082da1b43ab4",
                DisplayName = "tuple booking",
                MethodName = "Demo.TupleScenarios.Booking",
                Namespace = "Demo",
                TypeName = "TupleScenarios",
                ClassDisplayName = null,
                SourceFile = "",
                SourceLine = 78,
                Timeout = null,
                TeardownPolicy = (global::Raun.Run)0,
                Nodes = nodes,
                Method = typeof(global::Demo.TupleScenarios).GetMethod("Booking", global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.DeclaredOnly)
            };
        }
    }
}
