using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Raun.Generator.Lowering;
using Raun.Generator.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;
using static Raun.Generator.Syntax.Literals;

namespace Raun.Generator.Emit;

/// <summary>
/// Emits the generated C# source for the lowered scenarios as Roslyn syntax trees.
/// </summary>
/// <remarks>
/// One file per scenario, plus one registry file holding the module initializer and
/// <c>CreateAll</c> — every one of them a part of the same <c>Raun.Generated.RaunGenerated</c>
/// class. The split is what keeps an editor cheap: a scenario's file re-emits when that scenario
/// changes, and the registry's content is the scenario names alone, so it stands still while a step
/// body is being typed.
/// </remarks>
internal static class ScenarioEmitter
{
    /// <summary>The hint name prefix of a per-scenario file; the rest is the scenario's safe name.</summary>
    public const string ScenarioHintPrefix = "RaunScenario.";

    /// <summary>The hint name of the registry file.</summary>
    public const string RegistryHintName = "RaunScenarios.g.cs";

    /// <summary>One scenario's file: its builder method, under the usings its own source file carried.</summary>
    public static string EmitScenario(ParsedScenario scenario)
        => Render([scenario], [BuildScenarioBuilder(scenario)]);

    /// <summary>The registry file: <c>CreateAll</c> and the module initializer that registers every
    /// scenario. Built from the scenario names alone, never from what a step does.</summary>
    public static string EmitRegistry(IReadOnlyList<RegistryEntry> entries)
        => Render([], [BuildCreateAll(entries), BuildModuleInitializer(entries)]);

    private static string Render(
        IReadOnlyList<ParsedScenario> scenarios,
        IReadOnlyList<MemberDeclarationSyntax> members)
    {
        var classDecl = ClassDeclaration("RaunGenerated")
            .AddModifiers(
                Token(SyntaxKind.InternalKeyword),
                Token(SyntaxKind.StaticKeyword),
                Token(SyntaxKind.PartialKeyword))
            .WithMembers(List(members));

        var nsDecl = NamespaceDeclaration(Names.Dotted("Raun", "Generated")).AddMembers(classDecl);

        var unit = CompilationUnit()
            .WithUsings(List(CollectUsings(scenarios)))
            .AddMembers(nsDecl)
            .NormalizeWhitespace(eol: "\n");

        // The header and the file's final newline are trivia, attached AFTER normalization: they are
        // not part of the tree's shape and the normalizer has no reason to touch them.
        return unit
            .WithLeadingTrivia(Header)
            .WithEndOfFileToken(unit.EndOfFileToken.WithLeadingTrivia(EndOfLine("\n")))
            .ToFullString();
    }

    /// <summary><c>// &lt;auto-generated/&gt;</c>, <c>#nullable enable</c>,
    /// <c>#pragma warning disable CS1591</c>, <c>#line hidden</c>.</summary>
    private static SyntaxTriviaList Header => TriviaList(
        Comment("// <auto-generated/>"),
        EndOfLine("\n"),
        Directive(NullableDirectiveTrivia(Token(SyntaxKind.EnableKeyword), isActive: true)),
        EndOfLine("\n"),
        Directive(PragmaWarningDirectiveTrivia(Token(SyntaxKind.DisableKeyword), isActive: true)
            .WithErrorCodes(SingletonSeparatedList<ExpressionSyntax>(IdentifierName("CS1591")))),
        EndOfLine("\n"),
        Directive(LineDirectiveTrivia(Token(SyntaxKind.HiddenKeyword), isActive: true)),
        EndOfLine("\n"));

    /// <summary>A directive as trivia. Directive tokens carry no spacing of their own, and this
    /// trivia is attached after the file is normalized, so each one is normalized on its own — minus
    /// the line break normalization appends, which the header spells out itself.</summary>
    private static SyntaxTrivia Directive(DirectiveTriviaSyntax directive)
        => Trivia(directive.NormalizeWhitespace(eol: "\n").WithoutTrailingTrivia());

    /// <summary>The generated file's using directives: the three the emitted code always needs, then
    /// every directive the scenarios' own files carried, deduped on normalized text.</summary>
    private static IEnumerable<UsingDirectiveSyntax> CollectUsings(IReadOnlyList<ParsedScenario> scenarios)
    {
        var seen = new HashSet<string>();

        var required = new[]
        {
            UsingDirective(IdentifierName("Raun")),
            UsingDirective(Names.Dotted("System", "Linq")),
            UsingDirective(Names.Dotted("System", "Threading", "Tasks")),
        };

        foreach (var directive in required.Concat(scenarios.SelectMany(s => s.Usings)))
        {
            if (seen.Add(directive.NormalizeWhitespace().ToString()))
            {
                yield return directive;
            }
        }
    }

    private static MethodDeclarationSyntax BuildCreateAll(IReadOnlyList<RegistryEntry> scenarios)
    {
        ExpressionSyntax body;
        if (scenarios.Count == 0)
        {
            // global::System.Array.Empty<global::Raun.Model.ScenarioDefinition>()
            body = InvocationExpression(
                MemberAccessExpression(
                    SyntaxKind.SimpleMemberAccessExpression,
                    Names.Global("System", "Array"),
                    GenericName(Identifier("Empty"))
                        .WithTypeArgumentList(TypeArgumentList(SingletonSeparatedList<TypeSyntax>(
                            ScenarioDefinitionType)))))
                .WithArgumentList(ArgumentList());
        }
        else
        {
            // new global::Raun.Model.ScenarioDefinition[] { Scenario_X(), ... }
            var calls = scenarios.Select(s =>
                (ExpressionSyntax)InvocationExpression(IdentifierName($"Scenario_{s.SafeName}"))
                    .WithArgumentList(ArgumentList()));
            body = ArrayOf(ScenarioDefinitionType, calls);
        }

        return MethodDeclaration(
                Names.Generic(
                    Names.Global("System", "Collections", "Generic"),
                    "IReadOnlyList",
                    ScenarioDefinitionType),
                "CreateAll")
            .AddModifiers(Token(SyntaxKind.PublicKeyword), Token(SyntaxKind.StaticKeyword))
            .WithExpressionBody(ArrowExpressionClause(body))
            .WithSemicolonToken(Token(SyntaxKind.SemicolonToken));
    }

    private static MethodDeclarationSyntax BuildModuleInitializer(IReadOnlyList<RegistryEntry> scenarios)
    {
        // global::Raun.ScenarioRegistry.Register("...", Scenario_X);
        var statements = scenarios.Select(s =>
            (StatementSyntax)ExpressionStatement(
                InvocationExpression(
                    MemberAccessExpression(
                        SyntaxKind.SimpleMemberAccessExpression,
                        Names.Global("Raun", "ScenarioRegistry"),
                        IdentifierName("Register")))
                    .WithArgumentList(ArgumentList(SeparatedList<ArgumentSyntax>(new[]
                    {
                        Argument(Lit(s.MethodFullName)),
                        Argument(IdentifierName($"Scenario_{s.SafeName}")),
                    })))));

        return MethodDeclaration(PredefinedType(Token(SyntaxKind.VoidKeyword)), "Initialize")
            .AddAttributeLists(AttributeList(SingletonSeparatedList(
                Attribute(Names.Global("System", "Runtime", "CompilerServices", "ModuleInitializer")))))
            .AddModifiers(Token(SyntaxKind.InternalKeyword), Token(SyntaxKind.StaticKeyword))
            .WithBody(Block(statements));
    }

    private static MethodDeclarationSyntax BuildScenarioBuilder(ParsedScenario scenario)
    {
        // var nodes = new global::Raun.Model.ScenarioNode[N];
        var arrayExpr = ArrayCreationExpression(
            ArrayType(ScenarioNodeType)
                .WithRankSpecifiers(SingletonList(
                    ArrayRankSpecifier(SingletonSeparatedList<ExpressionSyntax>(
                        Num(scenario.Steps.Count))))));

        var nodesDecl = LocalDeclarationStatement(
            VariableDeclaration(IdentifierName("var"))
                .WithVariables(SingletonSeparatedList(
                    VariableDeclarator(Identifier("nodes"))
                        .WithInitializer(EqualsValueClause(arrayExpr)))));

        var statements = new List<StatementSyntax> { nodesDecl };

        foreach (var step in scenario.Steps)
        {
            var assignment = AssignmentExpression(
                SyntaxKind.SimpleAssignmentExpression,
                ElementAccessExpression(IdentifierName("nodes"))
                    .WithArgumentList(BracketedArgumentList(SingletonSeparatedList(Argument(Num(step.Index))))),
                BuildNode(step));
            statements.Add(ExpressionStatement(assignment));
        }

        var members = new List<ExpressionSyntax>
        {
            Set("ScenarioId", Lit(scenario.ScenarioId)),
            Set("DisplayName", Lit(scenario.DisplayName)),
            Set("MethodName", Lit(scenario.MethodFullName)),
            Set("Namespace", Lit(scenario.Namespace)),
            Set("TypeName", Lit(scenario.TypeName)),
            Set("ClassDisplayName", Lit(scenario.ClassDisplayName)),
            Set("SourceFile", Lit(scenario.SourceFile)),
            Set("SourceLine", Num(scenario.SourceLine)),
            Set("Timeout", Timeout(scenario.TimeoutMs)),
            Set("TeardownPolicy", CastExpression(Names.Global("Raun", "Run"), Num(scenario.TeardownPolicy))),
            Set("Nodes", IdentifierName("nodes")),
        };

        // Only when declared, so use-free scenarios emit exactly what they did before.
        if (scenario.Uses.Count > 0)
        {
            members.Add(Set("Uses", ArrayOf(
                Names.Global("Raun", "ContendedResourceUse"),
                scenario.Uses.Select(UseEntry))));
        }

        var definition = ObjectCreationExpression(ScenarioDefinitionType)
            .WithInitializer(InitializerExpression(SyntaxKind.ObjectInitializerExpression, SeparatedList(members)));

        statements.Add(ReturnStatement(definition));

        return MethodDeclaration(ScenarioDefinitionType, $"Scenario_{scenario.SafeName}")
            .AddModifiers(Token(SyntaxKind.PublicKeyword), Token(SyntaxKind.StaticKeyword))
            .WithBody(Block(statements));
    }

    /// <summary><c>new global::Raun.ContendedResourceUse(typeof(T), global::Raun.LockMode.Mode)</c>.</summary>
    private static ExpressionSyntax UseEntry(ParsedUse use)
        => ObjectCreationExpression(Names.Global("Raun", "ContendedResourceUse"))
            .WithArgumentList(ArgumentList(SeparatedList<ArgumentSyntax>(new[]
            {
                Argument(TypeOfExpression(use.Resource)),
                Argument(MemberAccessExpression(
                    SyntaxKind.SimpleMemberAccessExpression,
                    Names.Global("Raun", "LockMode"),
                    IdentifierName(use.Mode))),
            })));

    private static ObjectCreationExpressionSyntax BuildNode(ParsedStep step)
    {
        var members = new List<ExpressionSyntax>
        {
            Set("Index", Num(step.Index)),
            Set("StepId", Lit(step.StepId)),
            Set("Phase", Lit(step.Phase)),
            Set("OperationName", Lit(step.OperationName)),
            Set("DisplayNameTemplate", Lit(step.DisplayNameTemplate)),
            Set("SourceFile", Lit(step.SourceFile)),
            Set("SourceLine", Num(step.SourceLine)),
            Set("GroupId", Lit(step.GroupId)),
            Set("Timeout", Timeout(step.TimeoutMs)),
            Set("DependsOn", IntArray(step.DependsOn)),
        };

        // Conditional members: emitted only when non-default, so a scenario without conditionals
        // produces byte-identical output to before this feature (existing snapshots must not move).
        if (step.Guards.Count > 0)
        {
            members.Add(Set("Guards", GuardArray(step.Guards)));
        }

        if (step.MergeSources.Count > 0)
        {
            members.Add(Set("MergeSources", IntArray(step.MergeSources)));
        }

        if (step.WaitsFor.Count > 0)
        {
            members.Add(Set("WaitsFor", IntArray(step.WaitsFor)));
        }

        if (step.IsSynthetic)
        {
            members.Add(Set("IsSynthetic", LiteralExpression(SyntaxKind.TrueLiteralExpression)));
        }

        if (step.IsTeardown)
        {
            members.Add(Set("IsTeardown", LiteralExpression(SyntaxKind.TrueLiteralExpression)));
        }

        if (step.ConditionCoercionType is { } coercionType)
        {
            // static __o => ((T)__o!) ? true : false — Roslyn picks bool / implicit conversion /
            // operator true at COMPILE time, so the scheduler never reflects over the boxed output.
            members.Add(Set("EvaluateCondition",
                SimpleLambdaExpression(Parameter(Identifier("__o")))
                    .WithModifiers(TokenList(Token(SyntaxKind.StaticKeyword)))
                    .WithExpressionBody(ConditionalExpression(
                        ParenthesizedExpression(CastExpression(
                            coercionType,
                            PostfixUnaryExpression(
                                SyntaxKind.SuppressNullableWarningExpression,
                                IdentifierName("__o")))),
                        LiteralExpression(SyntaxKind.TrueLiteralExpression),
                        LiteralExpression(SyntaxKind.FalseLiteralExpression)))));
        }

        members.Add(Set("Invoke", BuildInvokeLambda(step)));

        if (step.FormatExpression is { } format)
        {
            members.Add(Set("FormatDisplayName",
                SimpleLambdaExpression(Parameter(Identifier("__inputs")))
                    .WithModifiers(TokenList(Token(SyntaxKind.StaticKeyword)))
                    .WithExpressionBody(format)));
        }

        return ObjectCreationExpression(ScenarioNodeType)
            .WithInitializer(InitializerExpression(SyntaxKind.ObjectInitializerExpression, SeparatedList(members)));
    }

    /// <summary>
    /// Builds: <c>static async (__inputs, __ctx) => { var __r = await CALL; [resource calls] return (object?)__r; }</c>
    /// or:     <c>static async (__inputs, __ctx) => { await CALL; [resource calls] return (object?)null; }</c>
    /// The line-mapped CALL statement stays FIRST; any <c>ctx.Resources.*</c> calls are inserted AFTER
    /// it with hidden trivia (so they don't perturb the call's source mapping); the return stays last.
    /// When the step has no resource roles, the body is byte-identical to the role-free output.
    /// </summary>
    private static ParenthesizedLambdaExpressionSyntax BuildInvokeLambda(ParsedStep step)
    {
        if (step.InvokeCall is not { } call)
        {
            // A merge/pass-through never runs: the scheduler resolves it from its sources; teardown is
            // run outside the DAG. The delegate exists only to satisfy the required member.
            return InvokeLambda()
                .WithExpressionBody(InvocationExpression(
                        MemberAccessExpression(
                            SyntaxKind.SimpleMemberAccessExpression,
                            Names.Global("System", "Threading", "Tasks", "Task"),
                            GenericName(Identifier("FromResult"))
                                .WithTypeArgumentList(TypeArgumentList(SingletonSeparatedList<TypeSyntax>(
                                    NullableType(PredefinedType(Token(SyntaxKind.ObjectKeyword))))))))
                    .WithArgumentList(ArgumentList(SingletonSeparatedList(
                        Argument(LiteralExpression(SyntaxKind.NullLiteralExpression))))));
        }

        var awaitExpr = AwaitExpression(call);

        StatementSyntax callStmt;
        StatementSyntax returnStmt;
        if (step.HasResult)
        {
            // var __r = await CALL;
            callStmt = LocalDeclarationStatement(
                VariableDeclaration(IdentifierName("var"))
                    .WithVariables(SingletonSeparatedList(
                        VariableDeclarator(Identifier("__r"))
                            .WithInitializer(EqualsValueClause(awaitExpr)))))
                .WithLeadingTrivia(LineMappedTrivia(step));
            // return (object?)__r;
            returnStmt = ReturnStatement(
                CastExpression(
                    NullableType(PredefinedType(Token(SyntaxKind.ObjectKeyword))),
                    IdentifierName("__r")))
                .WithLeadingTrivia(HiddenTrivia());
        }
        else
        {
            // await CALL;
            callStmt = ExpressionStatement(awaitExpr).WithLeadingTrivia(LineMappedTrivia(step));
            // return (object?)null;
            returnStmt = ReturnStatement(
                CastExpression(
                    NullableType(PredefinedType(Token(SyntaxKind.ObjectKeyword))),
                    LiteralExpression(SyntaxKind.NullLiteralExpression)))
                .WithLeadingTrivia(HiddenTrivia());
        }

        // No roles ⇒ [callStmt, returnStmt], identical to the prior output. Roles ⇒ declare what you
        // touch, then touch it: claims on the step's INPUTS go before the call, so a conflict with an
        // unordered sibling is refused before the step performs its real side effect; anything that
        // names the step's own return (__r) can only follow the call. Relative order is kept within
        // each half, so the effect stream still reads parameters first, then return.
        var bodyStatements = new List<StatementSyntax>();
        bodyStatements.AddRange(step.ResourceClaims.Where(c => !MentionsReturn(c)).Select(ResourceCallStatement));
        bodyStatements.Add(callStmt);
        bodyStatements.AddRange(step.ResourceClaims.Where(MentionsReturn).Select(ResourceCallStatement));
        bodyStatements.Add(returnStmt);

        return InvokeLambda()
            .AddModifiers(Token(SyntaxKind.AsyncKeyword))
            .WithBlock(Block(bodyStatements));
    }

    /// <summary><c>static (__inputs, __ctx) => …</c>, the shape of <c>ScenarioNode.Invoke</c>.</summary>
    private static ParenthesizedLambdaExpressionSyntax InvokeLambda()
        => ParenthesizedLambdaExpression()
            .WithModifiers(TokenList(Token(SyntaxKind.StaticKeyword)))
            .WithParameterList(ParameterList(SeparatedList(new[]
            {
                Parameter(Identifier("__inputs")),
                Parameter(Identifier("__ctx")),
            })));

    /// <summary>True when the claim's target or any of its lineage subjects is the step's own return
    /// value, which exists only after the DSL call has run.</summary>
    private static bool MentionsReturn(ResourceRoleClaim claim)
        => claim.IsReturn || IsReturnValue(claim.Expression) || claim.SubjectExpressions.Any(IsReturnValue);

    private static bool IsReturnValue(ExpressionSyntax expression)
        => expression is IdentifierNameSyntax { Identifier.ValueText: "__r" };

    /// <summary>
    /// Builds <c>await __ctx.Resources.{Verb}({Expression});</c> as a hidden-trivia expression
    /// statement, e.g. <c>await __ctx.Resources.Edit(__r);</c>. The verb is the runtime
    /// <c>ResourceContext</c> method name; the expression is the parameter argument (in terms of
    /// <c>__inputs</c>) or <c>__r</c> for a return role.
    /// </summary>
    private static StatementSyntax ResourceCallStatement(ResourceRoleClaim claim)
    {
        var arguments = new List<ArgumentSyntax> { Argument(claim.Expression) };
        foreach (var subject in claim.SubjectExpressions)
        {
            arguments.Add(Argument(subject));
        }

        var call = InvocationExpression(
            MemberAccessExpression(
                SyntaxKind.SimpleMemberAccessExpression,
                MemberAccessExpression(
                    SyntaxKind.SimpleMemberAccessExpression,
                    IdentifierName("__ctx"),
                    IdentifierName("Resources")),
                IdentifierName(claim.Verb)))
            .WithArgumentList(ArgumentList(SeparatedList(arguments)));

        return ExpressionStatement(AwaitExpression(call)).WithLeadingTrivia(HiddenTrivia());
    }

    private static SyntaxTriviaList HiddenTrivia()
        => TriviaList(Trivia(LineDirectiveTrivia(Token(SyntaxKind.HiddenKeyword), isActive: true)), EndOfLine("\n"));

    // NormalizeWhitespace indents the Invoke-lambda body to this column (5 levels x 4 spaces).
    // charOffset must equal the column where the call STATEMENT begins, so the statement's
    // sequence point (which starts at `var`/`await`) maps to the original invocation start.
    // Confirmed by the LineMappingPdbTests calibration.
    private const int LambdaBodyIndent = 20;

    private static SyntaxTriviaList LineMappedTrivia(ParsedStep step)
    {
        if (step.CallSpan is not { } span)
        {
            return TriviaList();   // pathless input ⇒ no directive (snapshot determinism)
        }

        var directive = LineSpanDirectiveTrivia(
            LineDirectivePosition(Literal(span.StartLine + 1), Literal(span.StartChar + 1)),   // 1-based
            LineDirectivePosition(Literal(span.EndLine + 1), Literal(span.EndChar + 1)),
            Literal(LambdaBodyIndent),
            Literal(span.File),
            isActive: true);
        return TriviaList(Trivia(directive), EndOfLine("\n"));
    }

    /// <summary>Builds <c>new global::Raun.Model.Guard[] { new(i, true), … }</c>.</summary>
    private static ArrayCreationExpressionSyntax GuardArray(IEnumerable<ParsedGuard> guards)
        => ArrayOf(
            Names.Global("Raun", "Model", "Guard"),
            guards.Select(g => (ExpressionSyntax)ObjectCreationExpression(Names.Global("Raun", "Model", "Guard"))
                .WithArgumentList(ArgumentList(SeparatedList<ArgumentSyntax>(new[]
                {
                    Argument(Num(g.ConditionIndex)),
                    Argument(LiteralExpression(g.WhenValue
                        ? SyntaxKind.TrueLiteralExpression
                        : SyntaxKind.FalseLiteralExpression)),
                })))));

    /// <summary>Builds <c>new int[] { i0, i1, … }</c> (empty initializer when the list is empty).</summary>
    private static ArrayCreationExpressionSyntax IntArray(IEnumerable<int> ints)
        => ArrayOf(PredefinedType(Token(SyntaxKind.IntKeyword)), ints.Select(Num));

    /// <summary>Builds <c>new T[] { … }</c>.</summary>
    private static ArrayCreationExpressionSyntax ArrayOf(TypeSyntax element, IEnumerable<ExpressionSyntax> items)
        => ArrayCreationExpression(
            ArrayType(element)
                .WithRankSpecifiers(SingletonList(
                    ArrayRankSpecifier(SingletonSeparatedList<ExpressionSyntax>(
                        OmittedArraySizeExpression())))))
            .WithInitializer(InitializerExpression(
                SyntaxKind.ArrayInitializerExpression,
                SeparatedList(items)));

    /// <summary>
    /// Builds <c>global::System.TimeSpan.FromMilliseconds(ms)</c> or <c>null</c> when ms &lt;= 0.
    /// </summary>
    private static ExpressionSyntax Timeout(int ms)
        => ms > 0
            ? InvocationExpression(
                MemberAccessExpression(
                    SyntaxKind.SimpleMemberAccessExpression,
                    Names.Global("System", "TimeSpan"),
                    IdentifierName("FromMilliseconds")))
                .WithArgumentList(ArgumentList(SingletonSeparatedList(Argument(Num(ms)))))
            : LiteralExpression(SyntaxKind.NullLiteralExpression);

    private static NameSyntax ScenarioDefinitionType => Names.Global("Raun", "Model", "ScenarioDefinition");

    private static NameSyntax ScenarioNodeType => Names.Global("Raun", "Model", "ScenarioNode");

    private static AssignmentExpressionSyntax Set(string member, ExpressionSyntax value)
        => AssignmentExpression(SyntaxKind.SimpleAssignmentExpression, IdentifierName(member), value);

    private static LiteralExpressionSyntax Lit(string? value)
        => value is null
            ? LiteralExpression(SyntaxKind.NullLiteralExpression)
            : LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(value));
}
